SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

CREATE DATABASE IF NOT EXISTS `dartDB` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `dartDB`;

CREATE TABLE IF NOT EXISTS `stats` (
  `MISSES` int(11) DEFAULT NULL,
  `NAME` varchar(50) NOT NULL DEFAULT PRIMARY KEY''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
